MENU_ITEMS = [
    {
        "id": "IT_157237157",
        "name": "Chakli Schezwan",
        "price": 330.0,
        "tags": [],
        "category": "Chakna",
    },
    {
        "id": "IT_157237158",
        "name": "Masala Peanut",
        "price": 300.0,
        "tags": [],
        "category": "Chakna",
    },
    {
        "id": "IT_157237159",
        "name": "Rumali Cheese Papad",
        "price": 385.0,
        "tags": [],
        "category": "Chakna",
    },
    {
        "id": "IT_157237160",
        "name": "Chakna Platter",
        "price": 550.0,
        "tags": [],
        "category": "Chakna",
    },
    {
        "id": "IT_157237161",
        "name": "Chole Peanut Chat",
        "price": 300.0,
        "tags": [],
        "category": "Chakna",
    },
    {
        "id": "IT_1285276383",
        "name": "Salted Peanut",
        "price": 80.0,
        "tags": [],
        "category": "Chakna",
    },
    {
        "id": "IT_1285277898",
        "name": "Chana Chat",
        "price": 300.0,
        "tags": [],
        "category": "Chakna",
    },
    {
        "id": "IT_1285076046",
        "name": "Cold Brew Black",
        "price": 250.0,
        "tags": [],
        "category": "Cold Brew",
    },
    {
        "id": "IT_1285076047",
        "name": "Cold Brew Latte",
        "price": 275.0,
        "tags": [],
        "category": "Cold Brew",
    },
    {
        "id": "IT_1285076048",
        "name": "Elderflower Cold Brew",
        "price": 275.0,
        "tags": [],
        "category": "Cold Brew",
    },
    {
        "id": "IT_1285076049",
        "name": "Sunrise Cold Brew",
        "price": 275.0,
        "tags": [],
        "category": "Cold Brew",
    },
    {
        "id": "IT_1285076050",
        "name": "Pineapple Cold Brew",
        "price": 275.0,
        "tags": [],
        "category": "Cold Brew",
    },
    {
        "id": "IT_1285076051",
        "name": "Cold Brew With Tonic",
        "price": 350.0,
        "tags": [],
        "category": "Cold Brew",
    },
    {
        "id": "IT_1285076123",
        "name": "Koffee Kul",
        "price": 210.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076124",
        "name": "Culture Frappe",
        "price": 220.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076125",
        "name": "Choco Frappe",
        "price": 220.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076126",
        "name": "Classic Irish",
        "price": 275.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076127",
        "name": "Nutty Milano",
        "price": 275.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076128",
        "name": "Coffee Chocolate Shake",
        "price": 295.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076129",
        "name": "Chocolate Brownie Mochochillo",
        "price": 295.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076130",
        "name": "Coffee Ice Blended Frappe",
        "price": 250.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076131",
        "name": "Mocha Ice Blended Frappe",
        "price": 295.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076132",
        "name": "Biscoff Ice Blended Frappe",
        "price": 300.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076133",
        "name": "Culture Addiction",
        "price": 350.0,
        "tags": [],
        "category": "Cold Coffee",
    },
    {
        "id": "IT_1285076113",
        "name": "Espresso",
        "price": 150.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076114",
        "name": "Americano",
        "price": 200.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076115",
        "name": "Hot Chocolate",
        "price": 200.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076116",
        "name": "Cappuccino",
        "price": 210.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076117",
        "name": "Latte",
        "price": 220.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076118",
        "name": "Mocha",
        "price": 250.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076119",
        "name": "White Chocolate Mocha",
        "price": 250.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076120",
        "name": "Irish Latte",
        "price": 250.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076121",
        "name": "Roasted Hazelnut Latte",
        "price": 250.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076122",
        "name": "Irish Americano",
        "price": 250.0,
        "tags": [],
        "category": "Hot Brew",
    },
    {
        "id": "IT_1285076045",
        "name": "Siphon",
        "price": 250.0,
        "tags": [],
        "category": "Manual Brew",
    },
    {
        "id": "IT_1285076134",
        "name": "French Press",
        "price": 250.0,
        "tags": [],
        "category": "Manual Brew",
    },
    {
        "id": "IT_1285076135",
        "name": "Aeropress",
        "price": 250.0,
        "tags": [],
        "category": "Manual Brew",
    },
    {
        "id": "IT_1285076136",
        "name": "V60 Pour Over",
        "price": 250.0,
        "tags": [],
        "category": "Manual Brew",
    },
    {
        "id": "IT_157237184",
        "name": "Bharwa Aloo",
        "price": 399.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237185",
        "name": "Baby Tandoori Aloo",
        "price": 399.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237186",
        "name": "Veg. Seekh Kebab",
        "price": 399.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237187",
        "name": "Hara Bhara Kebab",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237188",
        "name": "Tandoori Mushroom",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237189",
        "name": "Tandoori Bbq Paneer Tikka",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237190",
        "name": "Tandoori Paneer Tikka",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237191",
        "name": "Afghani Soya Chaap",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237192",
        "name": "Hyderabadi Soya Chaap",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237193",
        "name": "Tandoori Soya Chaap",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237194",
        "name": "Hara Masale Ka Bhuna Paneer",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237195",
        "name": "Malai Paneer Tikka",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237196",
        "name": "Paneer Kali Mari Tikka",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237197",
        "name": "Paneer Hydrabadi Tikka",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237198",
        "name": "Paneer Jamuni Tikka",
        "price": 490.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237199",
        "name": "Agarwali Aloo Tikki",
        "price": 399.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237200",
        "name": "Hadipa Paneer Tikka",
        "price": 460.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237201",
        "name": "Paneer Lasooni Cheese Tikka",
        "price": 520.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237202",
        "name": "Daman Culturess Kebab Platter",
        "price": 1499.0,
        "tags": [],
        "category": "Starters Tandoori Starter(Paneer/Soya Chaap/Veg)",
    },
    {
        "id": "IT_157237162",
        "name": "Sweet Corn Soup",
        "price": 330.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237163",
        "name": "Hot & Sour Soup",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237164",
        "name": "Dal Shorba",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237165",
        "name": "Tomato Shorba",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237166",
        "name": "Palak Shorba",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237167",
        "name": "Roasted Veg. Soup",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237168",
        "name": "Asian Mixed Green Soup",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237169",
        "name": "Tortilla Soup",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237170",
        "name": "Lemon Coriander Soup",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237171",
        "name": "Manchow Soup",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237172",
        "name": "Tomato Basil Soup",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237173",
        "name": "Broccoli Almond Soup",
        "price": 385.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237174",
        "name": "Cream Of Mushroom Soup",
        "price": 440.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237175",
        "name": "Wild Mushroom Soup",
        "price": 440.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237176",
        "name": "Burmese Khow Soup",
        "price": 495.0,
        "tags": [],
        "category": "Soup / Shorba",
    },
    {
        "id": "IT_157237177",
        "name": "Size Zero Salad",
        "price": 330.0,
        "tags": [],
        "category": "Salad",
    },
    {
        "id": "IT_157237178",
        "name": "Tandoori Paneer Salad",
        "price": 330.0,
        "tags": [],
        "category": "Salad",
    },
    {
        "id": "IT_157237179",
        "name": "Classic Greek Feta Salad",
        "price": 385.0,
        "tags": [],
        "category": "Salad",
    },
    {
        "id": "IT_157237180",
        "name": "Watermelon Feta Salad",
        "price": 385.0,
        "tags": [],
        "category": "Salad",
    },
    {
        "id": "IT_157237181",
        "name": "Best Broccoli Salad",
        "price": 385.0,
        "tags": [],
        "category": "Salad",
    },
    {
        "id": "IT_157237182",
        "name": "Russian Salad",
        "price": 400.0,
        "tags": [],
        "category": "Salad",
    },
    {
        "id": "IT_157237183",
        "name": "Sprouts Salad",
        "price": 400.0,
        "tags": [],
        "category": "Salad",
    },
    {
        "id": "IT_1285295793",
        "name": "Garden Salad",
        "price": 250.0,
        "tags": [],
        "category": "Salad",
    },
    {
        "id": "IT_157237203",
        "name": "Honey Chilli Potato",
        "price": 399.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237204",
        "name": "Spinach Cheese Roll",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237205",
        "name": "Mushroom Paneer Cheese Roll",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237206",
        "name": "Dragon Potato",
        "price": 399.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237207",
        "name": "Vegetable 65",
        "price": 399.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237208",
        "name": "Crispy Vegetable",
        "price": 399.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237209",
        "name": "Spring Roll",
        "price": 399.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237210",
        "name": "Mushroom Chilly",
        "price": 399.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237211",
        "name": "Paneer 65",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237212",
        "name": "Dragon Spring Roll",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237213",
        "name": "Mushroom Chilly (chinese)",
        "price": 399.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237214",
        "name": "Manchurian",
        "price": 399.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237215",
        "name": "Veg Lolipop",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237216",
        "name": "Chilli Paneer",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237217",
        "name": "Paneer Shanghai",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237218",
        "name": "Crispy Paneer Dry",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237219",
        "name": "Baby Corn Salt & Pepper",
        "price": 405.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237220",
        "name": "Super Mario Mushroom",
        "price": 520.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237221",
        "name": "Greek Bambas",
        "price": 520.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237222",
        "name": "Jade Mashroom",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Starters",
    },
    {
        "id": "IT_157237223",
        "name": "French Fries",
        "price": 230.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237224",
        "name": "Garlic Bread Cheese",
        "price": 290.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237225",
        "name": "Cheese Cigar Roll",
        "price": 399.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237226",
        "name": "Old School Onion Rings",
        "price": 375.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237227",
        "name": "Best Ever Jalapeno Poppers",
        "price": 490.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237228",
        "name": "Bbq Cauliflower Wings",
        "price": 399.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237229",
        "name": "Loaded Nachos",
        "price": 550.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237230",
        "name": "Lean Green Nachos",
        "price": 550.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237231",
        "name": "Corn Cheese Balls",
        "price": 490.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237232",
        "name": "Cheesy Bruschetta",
        "price": 475.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_1285253946",
        "name": "French Fries Peri Peri",
        "price": 240.0,
        "tags": [],
        "category": "Continental Starters",
    },
    {
        "id": "IT_157237233",
        "name": "Labanese Falafal Wrap",
        "price": 460.0,
        "tags": [],
        "category": "Continental Main Course",
    },
    {
        "id": "IT_157237234",
        "name": "Og Falafal",
        "price": 520.0,
        "tags": [],
        "category": "Continental Main Course",
    },
    {
        "id": "IT_157237235",
        "name": "Mediterian Mezze Platter",
        "price": 550.0,
        "tags": [],
        "category": "Continental Main Course",
    },
    {
        "id": "IT_157237236",
        "name": "Lebanese Bowl",
        "price": 570.0,
        "tags": [],
        "category": "Continental Main Course",
    },
    {
        "id": "IT_157237237",
        "name": "Mexican Burrito Bowl",
        "price": 690.0,
        "tags": [],
        "category": "Continental Main Course",
    },
    {
        "id": "IT_157237238",
        "name": "Maggi Sizzler",
        "price": 500.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237239",
        "name": "Pasta Sizzler",
        "price": 920.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237240",
        "name": "Paneer Sizzler",
        "price": 920.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237241",
        "name": "China Town Sizzler",
        "price": 920.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237242",
        "name": "3c Sizzler",
        "price": 1040.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237243",
        "name": "Paneer Shashlik Sizzler In Makhani Gravy",
        "price": 920.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237244",
        "name": "Mix Grill Sizzler",
        "price": 920.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237245",
        "name": "Mexican Sizzler",
        "price": 980.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237246",
        "name": "Mexican Chimichanga Sizzler",
        "price": 1040.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237247",
        "name": "Chinese Combo Sizzler",
        "price": 1040.0,
        "tags": [],
        "category": "Sizzler",
    },
    {
        "id": "IT_157237248",
        "name": "Masala Mafia Risotto",
        "price": 570.0,
        "tags": [],
        "category": "Risotto",
    },
    {
        "id": "IT_157237249",
        "name": "Quattro Formaggi Risotto",
        "price": 570.0,
        "tags": [],
        "category": "Risotto",
    },
    {
        "id": "IT_157237250",
        "name": "Portofino Penne",
        "price": 399.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237251",
        "name": "Arrabiata Pasta",
        "price": 399.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237252",
        "name": "Alfredo Pasta",
        "price": 399.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237253",
        "name": "Combination Pasta",
        "price": 460.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237254",
        "name": "Pomodoro Basilica Spaghetti",
        "price": 520.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237255",
        "name": "Baked Alforno",
        "price": 570.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237256",
        "name": "Baked Spaghetti Mozarella",
        "price": 570.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237257",
        "name": "Barbaresca Penne",
        "price": 570.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237258",
        "name": "Mac N Cheese Pasta",
        "price": 575.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237259",
        "name": "Layered Pasta",
        "price": 690.0,
        "tags": [],
        "category": "Pasta",
    },
    {
        "id": "IT_157237260",
        "name": "Margherita Pizza",
        "price": 399.0,
        "tags": [],
        "category": "Thin Crust Pizzas",
    },
    {
        "id": "IT_157237261",
        "name": "Peppy Paneer Pizza",
        "price": 599.0,
        "tags": [],
        "category": "Thin Crust Pizzas",
    },
    {
        "id": "IT_157237262",
        "name": "Paneer Bhurji Pizza",
        "price": 520.0,
        "tags": [],
        "category": "Thin Crust Pizzas",
    },
    {
        "id": "IT_157237263",
        "name": "Farmhouse Feast Pizza",
        "price": 640.0,
        "tags": [],
        "category": "Thin Crust Pizzas",
    },
    {
        "id": "IT_157237264",
        "name": "The Italian Connection Pizza",
        "price": 640.0,
        "tags": [],
        "category": "Thin Crust Pizzas",
    },
    {
        "id": "IT_157237265",
        "name": "Desi Dhamaka Pizza",
        "price": 599.0,
        "tags": [],
        "category": "Thin Crust Pizzas",
    },
    {
        "id": "IT_157237266",
        "name": "Exotic Veg In Hot Garlic Sauce",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Main Course",
    },
    {
        "id": "IT_157237267",
        "name": "Exotic Veg In Schezwan Sauce",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Main Course",
    },
    {
        "id": "IT_157237268",
        "name": "Cottage Cheese In Green Garlic Sauce",
        "price": 520.0,
        "tags": [],
        "category": "Chinese Main Course",
    },
    {
        "id": "IT_157237269",
        "name": "Cottage Cheese In Schezwan Sauce",
        "price": 520.0,
        "tags": [],
        "category": "Chinese Main Course",
    },
    {
        "id": "IT_157237270",
        "name": "Mushroom Chilli Gravy",
        "price": 520.0,
        "tags": [],
        "category": "Chinese Main Course",
    },
    {
        "id": "IT_157237271",
        "name": "Thai Rice Bowl",
        "price": 565.0,
        "tags": [],
        "category": "Chinese Main Course",
    },
    {
        "id": "IT_157237272",
        "name": "Veg Fried Rice",
        "price": 405.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237273",
        "name": "Hakka Noodles",
        "price": 405.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237274",
        "name": "Singapore Noodles",
        "price": 405.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237275",
        "name": "Schezwan Noodles",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237276",
        "name": "Schezwan Fried Rice",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237277",
        "name": "Chili Garlic Noodles",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237278",
        "name": "Chinese Bhel",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237279",
        "name": "Burnt Garlic Fried Rice",
        "price": 460.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237280",
        "name": "Pad Thai Noodles",
        "price": 520.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237281",
        "name": "Triple Fried Rice",
        "price": 520.0,
        "tags": [],
        "category": "Chinese Rice & Noodles",
    },
    {
        "id": "IT_157237282",
        "name": "Paneer Tikka Masala",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237283",
        "name": "Paneer Butter Masala",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237284",
        "name": "Palak Paneer",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237285",
        "name": "Paneer Makhanwala",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237286",
        "name": "Paneer Cheese Roll Masala",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237287",
        "name": "Paneer Patiyala",
        "price": 555.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237288",
        "name": "Kepco Paneer Masala",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237289",
        "name": "Paneer Lababdar",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237290",
        "name": "Paneer Bhurji",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237291",
        "name": "Kaju Mutter Paneer Masala",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237292",
        "name": "Cheese Butter Masala",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237293",
        "name": "Makhamali Tawa Paneer Chatakedar",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237294",
        "name": "Paneer Tirchi Mirchi",
        "price": 555.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237295",
        "name": "Paneer Takatak",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237296",
        "name": "Grilled Paneer Masala",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237297",
        "name": "Paneer Do Pyaza",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237298",
        "name": "Paneer Angara",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237299",
        "name": "Kaju Curry",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237300",
        "name": "Paneer Rajala",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237301",
        "name": "Paneer Toofani Chatpata",
        "price": 555.0,
        "tags": [],
        "category": "Indian Main Course Paneer Gravy",
    },
    {
        "id": "IT_157237302",
        "name": "Jeera Aloo Chatpata",
        "price": 345.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237303",
        "name": "Mushroom Masala",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237304",
        "name": "Sabzi Handi",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237305",
        "name": "Amritsari Chhole",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237306",
        "name": "Aloo Gobi Chatakedar",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237307",
        "name": "Mushroom Hara Pyaz Masala",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237308",
        "name": "Handi Jaikedar",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237309",
        "name": "Corn Capsicum Chatakedar",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237310",
        "name": "Veg Makhanwala",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237311",
        "name": "Methi Mutter Malai",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237312",
        "name": "Veg Kheema Masala",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237313",
        "name": "Sabzi Hara Lasooni",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237314",
        "name": "Veg Kolhapuri",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237315",
        "name": "Diwani Handi",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237316",
        "name": "Sabji Tal-mel",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237317",
        "name": "Banarashi Aloo Masala",
        "price": 460.0,
        "tags": [],
        "category": "Indian Main Course Sabzi",
    },
    {
        "id": "IT_157237318",
        "name": "Malai Kofta",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course",
    },
    {
        "id": "IT_157237319",
        "name": "Birbali Kofta",
        "price": 520.0,
        "tags": [],
        "category": "Indian Main Course",
    },
    {
        "id": "IT_157237320",
        "name": "Mini Chui-mui Kofta",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course",
    },
    {
        "id": "IT_157237321",
        "name": "Apricot Malai Kofta",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course",
    },
    {
        "id": "IT_157237322",
        "name": "Rishta Sham-savera Kofta",
        "price": 570.0,
        "tags": [],
        "category": "Indian Main Course",
    },
    {
        "id": "IT_157237323",
        "name": "Steam Rice",
        "price": 290.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237324",
        "name": "Jeera Rice",
        "price": 345.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237325",
        "name": "Curd Rice",
        "price": 345.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237326",
        "name": "Dal Khichdi",
        "price": 345.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237327",
        "name": "Kashmiri Pulao",
        "price": 345.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237328",
        "name": "Palak Dal Khichdi",
        "price": 405.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237329",
        "name": "Khichadi Dal Tadka",
        "price": 405.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237330",
        "name": "Avadhi Biryani",
        "price": 520.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237331",
        "name": "Hydarabadi Biryani",
        "price": 520.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237332",
        "name": "Peshawari Biryani",
        "price": 520.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237333",
        "name": "Mumbai Dum Biryani",
        "price": 520.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237334",
        "name": "Delhi Matka Biryani",
        "price": 570.0,
        "tags": [],
        "category": "Rice / Biryani / Khichdi",
    },
    {
        "id": "IT_157237335",
        "name": "Dal Fry",
        "price": 330.0,
        "tags": [],
        "category": "Dal",
    },
    {
        "id": "IT_157237336",
        "name": "Dal Tadka",
        "price": 349.0,
        "tags": [],
        "category": "Dal",
    },
    {
        "id": "IT_157237337",
        "name": "Gujrati Kadhi",
        "price": 330.0,
        "tags": [],
        "category": "Dal",
    },
    {
        "id": "IT_157237338",
        "name": "Dal Makhani",
        "price": 385.0,
        "tags": [],
        "category": "Dal",
    },
    {
        "id": "IT_157237339",
        "name": "Dal Palak",
        "price": 385.0,
        "tags": [],
        "category": "Dal",
    },
    {
        "id": "IT_157237340",
        "name": "Punjabi Kadai Pakoda",
        "price": 385.0,
        "tags": [],
        "category": "Dal",
    },
    {
        "id": "IT_157237341",
        "name": "Punjabi Dal Tadka",
        "price": 385.0,
        "tags": [],
        "category": "Dal",
    },
    {
        "id": "IT_157237342",
        "name": "Roti",
        "price": 45.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237343",
        "name": "Butter Roti",
        "price": 55.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237344",
        "name": "Naan",
        "price": 65.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237345",
        "name": "Missi Roti",
        "price": 65.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237346",
        "name": "Pudeena Roti",
        "price": 65.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237347",
        "name": "Kulcha",
        "price": 65.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237348",
        "name": "Khasta Roti",
        "price": 75.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237349",
        "name": "Butter Naan",
        "price": 75.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237350",
        "name": "Garlic Naan",
        "price": 85.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237351",
        "name": "Basil Garlic Naan",
        "price": 85.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237352",
        "name": "Laccha Paratha",
        "price": 85.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237353",
        "name": "Cheeses Naan",
        "price": 115.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237354",
        "name": "Cheese Chili Garlic Naan",
        "price": 125.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237355",
        "name": "Aloo Paratha",
        "price": 155.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237356",
        "name": "Gobi Paratha",
        "price": 155.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237357",
        "name": "Onion Paratha",
        "price": 155.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237358",
        "name": "Stuffed Paratha",
        "price": 155.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237359",
        "name": "Paneer Paratha",
        "price": 185.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237360",
        "name": "Cheese Paratha",
        "price": 185.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237361",
        "name": "Roti Basket (7 Types Of Plain Bread)",
        "price": 475.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_1285105372",
        "name": "Tawa Chapati",
        "price": 45.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_1285105546",
        "name": "Butter Tawa Chapati",
        "price": 55.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_1289461012",
        "name": "Butter Kulcha",
        "price": 75.0,
        "tags": [],
        "category": "Bread / Roti",
    },
    {
        "id": "IT_157237362",
        "name": "Roasted Papad",
        "price": 70.0,
        "tags": [],
        "category": "Papad",
    },
    {
        "id": "IT_157237363",
        "name": "Fry Papad",
        "price": 75.0,
        "tags": [],
        "category": "Papad",
    },
    {
        "id": "IT_157237364",
        "name": "Masala Papad Fry",
        "price": 125.0,
        "tags": [],
        "category": "Papad",
    },
    {
        "id": "IT_157237365",
        "name": "Roasted Masala Papad",
        "price": 125.0,
        "tags": [],
        "category": "Papad",
    },
    {
        "id": "IT_157237366",
        "name": "Daman Culture's Special Masala Papad",
        "price": 175.0,
        "tags": [],
        "category": "Papad",
    },
    {
        "id": "IT_157237367",
        "name": "Curd",
        "price": 100.0,
        "tags": [],
        "category": "Raita",
    },
    {
        "id": "IT_157237368",
        "name": "Boondi Raita",
        "price": 150.0,
        "tags": [],
        "category": "Raita",
    },
    {
        "id": "IT_157237369",
        "name": "Cucumber Raita",
        "price": 150.0,
        "tags": [],
        "category": "Raita",
    },
    {
        "id": "IT_157237370",
        "name": "Pineapple Raita",
        "price": 150.0,
        "tags": [],
        "category": "Raita",
    },
    {
        "id": "IT_157237371",
        "name": "Mix-veg Raita",
        "price": 175.0,
        "tags": [],
        "category": "Raita",
    },
    {
        "id": "IT_157237372",
        "name": "Walnut Brownie With Chocolate Sauce",
        "price": 250.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237373",
        "name": "New York Cheese Cake",
        "price": 250.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237374",
        "name": "Sizzling Brownie",
        "price": 300.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237375",
        "name": "Nutella Cheese Cake",
        "price": 350.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237376",
        "name": "Blueberry Cheese Cake",
        "price": 350.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237377",
        "name": "Biscoff Cheese Cake",
        "price": 350.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237378",
        "name": "Nutella Waffle",
        "price": 400.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237379",
        "name": "Chocolate Overload Waffle",
        "price": 400.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237380",
        "name": "Kitkat Waffle",
        "price": 400.0,
        "tags": [],
        "category": "Dessert",
    },
    {
        "id": "IT_157237381",
        "name": "Bbq On Table",
        "price": 2499.0,
        "tags": [],
        "category": "Bbq On Table",
    },
    {
        "id": "IT_1285072347",
        "name": "Qua Mineral Water",
        "price": 100.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285072348",
        "name": "Thumps Up Can",
        "price": 85.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285072349",
        "name": "Sprite Can",
        "price": 85.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285072350",
        "name": "Coke Can",
        "price": 85.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285072351",
        "name": "Diet Coke",
        "price": 85.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285072352",
        "name": "Tonic Water",
        "price": 120.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285072353",
        "name": "Red Bull",
        "price": 185.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285072354",
        "name": "Ginger Ale",
        "price": 120.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285075840",
        "name": "Soda Bottle",
        "price": 110.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285315921",
        "name": "Cranberry Juice",
        "price": 150.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285315974",
        "name": "Orange Juice",
        "price": 150.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285316006",
        "name": "Real Juice",
        "price": 150.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285319344",
        "name": "Fresh Lemon Soda",
        "price": 140.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285319353",
        "name": "Fresh Lemon Water",
        "price": 120.0,
        "tags": [],
        "category": "Beverage",
    },
    {
        "id": "IT_1285105991",
        "name": "Butter Millk",
        "price": 150.0,
        "tags": [],
        "category": "Accompaniments",
    },
    {
        "id": "IT_1285106002",
        "name": "Masala Butter Millk",
        "price": 165.0,
        "tags": [],
        "category": "Accompaniments",
    },
    {
        "id": "IT_1285106014",
        "name": "Plain Curd",
        "price": 100.0,
        "tags": [],
        "category": "Accompaniments",
    },
    {
        "id": "IT_157237382",
        "name": "Orange Pop",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237383",
        "name": "South Slide",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237384",
        "name": "Oww-some",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237385",
        "name": "Sensational Mango",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237386",
        "name": "Strawberry & Mint Suprise",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237387",
        "name": "Virgen Pinacolada",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237388",
        "name": "Virgin Blue Lagon",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237389",
        "name": "Trichum",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237390",
        "name": "Blue Boom",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237391",
        "name": "Wild Guava",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237392",
        "name": "Basil & Cucumber Passion",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237393",
        "name": "Fresh Me Up",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_1285145733",
        "name": "Virgin Mojito",
        "price": 425.0,
        "tags": [],
        "category": "Mocktails Signature",
    },
    {
        "id": "IT_157237394",
        "name": "Jamuni Julep",
        "price": 549.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237395",
        "name": "Snow White",
        "price": 599.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237396",
        "name": "Charming Cuban",
        "price": 599.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237397",
        "name": "Gin Twist",
        "price": 599.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237398",
        "name": "The Godfather 2.0",
        "price": 599.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237399",
        "name": "Porn Star Martini",
        "price": 649.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237400",
        "name": "Dc Ivory",
        "price": 599.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237401",
        "name": "Senorita",
        "price": 599.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237402",
        "name": "Botanist Drip",
        "price": 649.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237403",
        "name": "Thirsty Tipple",
        "price": 649.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237404",
        "name": "Wake Me Up",
        "price": 649.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237405",
        "name": "Sex On The Beach",
        "price": 649.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237406",
        "name": "Lavender Magrita",
        "price": 649.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237407",
        "name": "Pina Colada",
        "price": 649.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237408",
        "name": "Painkiller",
        "price": 649.0,
        "tags": [],
        "category": "Cocktails",
    },
    {
        "id": "IT_157237409",
        "name": "Daiquri",
        "price": 499.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237410",
        "name": "Mosco Mule",
        "price": 549.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237411",
        "name": "Cosmopoliton",
        "price": 549.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237412",
        "name": "Espresso Martini",
        "price": 549.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237413",
        "name": "Long Island Ice Tea",
        "price": 749.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237414",
        "name": "Whisky Sour",
        "price": 599.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237415",
        "name": "Penicillin",
        "price": 599.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237416",
        "name": "Breakfast Martini",
        "price": 599.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237417",
        "name": "Margarita",
        "price": 599.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237418",
        "name": "Trashcan",
        "price": 649.0,
        "tags": [],
        "category": "Classic Cocktails",
    },
    {
        "id": "IT_157237419",
        "name": "Summer Style",
        "price": 645.0,
        "tags": [],
        "category": "Signature Cocktails",
    },
    {
        "id": "IT_157237420",
        "name": "Forbidden",
        "price": 645.0,
        "tags": [],
        "category": "Signature Cocktails",
    },
    {
        "id": "IT_157237421",
        "name": "Be With Gin",
        "price": 645.0,
        "tags": [],
        "category": "Signature Cocktails",
    },
    {
        "id": "IT_157237422",
        "name": "Gtea",
        "price": 645.0,
        "tags": [],
        "category": "Signature Cocktails",
    },
    {
        "id": "IT_157237423",
        "name": "Addiction",
        "price": 645.0,
        "tags": [],
        "category": "Signature Cocktails",
    },
    {
        "id": "IT_157237424",
        "name": "Cabu Shots",
        "price": 375.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237425",
        "name": "Baileys Shots",
        "price": 450.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237426",
        "name": "Herbal Shot Shots",
        "price": 499.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237427",
        "name": "Cold Brew Shots Shots",
        "price": 499.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237428",
        "name": "White Slide Shots",
        "price": 499.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237429",
        "name": "Thai Bomb Shots",
        "price": 499.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237430",
        "name": "Jagermiester Shots",
        "price": 525.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237431",
        "name": "Jager Bomb Shots",
        "price": 699.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237432",
        "name": "Kamikaze Shots",
        "price": 499.0,
        "tags": [],
        "category": "Shots",
    },
    {
        "id": "IT_157237433",
        "name": "Black Dog Whisky",
        "price": 450.0,
        "tags": [],
        "category": "Regular Whisky (30Ml.)",
    },
    {
        "id": "IT_157237434",
        "name": "Jim Beam Whisky",
        "price": 300.0,
        "tags": [],
        "category": "Regular Whisky (30Ml.)",
    },
    {
        "id": "IT_157237435",
        "name": "Black & White Whisky",
        "price": 300.0,
        "tags": [],
        "category": "Regular Whisky (30Ml.)",
    },
    {
        "id": "IT_157237436",
        "name": "100 Pipers (12 Years) Whisky",
        "price": 350.0,
        "tags": [],
        "category": "Regular Whisky (30Ml.)",
    },
    {
        "id": "IT_157237437",
        "name": "Teachers Reserve Whisky",
        "price": 350.0,
        "tags": [],
        "category": "Regular Whisky (30Ml.)",
    },
    {
        "id": "IT_157237438",
        "name": "Jack Daniels Whisky",
        "price": 450.0,
        "tags": [],
        "category": "Regular Whisky (30Ml.)",
    },
    {
        "id": "IT_157237439",
        "name": "Jameson Whisky",
        "price": 400.0,
        "tags": [],
        "category": "Regular Whisky (30Ml.)",
    },
    {
        "id": "IT_157237440",
        "name": "Jameson Caskmates Whisky",
        "price": 450.0,
        "tags": [],
        "category": "Regular Whisky (30Ml.)",
    },
    {
        "id": "IT_157237441",
        "name": "Suntori Toki Whisky",
        "price": 650.0,
        "tags": [],
        "category": "Japanese Whisky (30Ml.)",
    },
    {
        "id": "IT_157237442",
        "name": "Old Monk Rum",
        "price": 199.0,
        "tags": [],
        "category": "Rum (30Ml.)",
    },
    {
        "id": "IT_157237443",
        "name": "Camino Gold Tequila",
        "price": 350.0,
        "tags": [],
        "category": "Tequilla (30Ml.)",
    },
    {
        "id": "IT_157237444",
        "name": "Patron Silver Tequila",
        "price": 550.0,
        "tags": [],
        "category": "Tequilla (30Ml.)",
    },
    {
        "id": "IT_157237445",
        "name": "Dewar's White Label Blended Scotch Whisky",
        "price": 250.0,
        "tags": [],
        "category": "Blended Scotch Whisky (30Ml.)",
    },
    {
        "id": "IT_157237446",
        "name": "Ballantines Blended Scotch Whisky",
        "price": 350.0,
        "tags": [],
        "category": "Blended Scotch Whisky (30Ml.)",
    },
    {
        "id": "IT_157237447",
        "name": "Johnnie Walker Red Label Blended Scotch Whisky",
        "price": 350.0,
        "tags": [],
        "category": "Blended Scotch Whisky (30Ml.)",
    },
    {
        "id": "IT_157237448",
        "name": "Monkey Shoulder Blended Scotch Whisky",
        "price": 495.0,
        "tags": [],
        "category": "Blended Scotch Whisky (30Ml.)",
    },
    {
        "id": "IT_157237449",
        "name": "Johnnie Walker Black Label Blended Scotch Whisky",
        "price": 495.0,
        "tags": [],
        "category": "Blended Scotch Whisky (30Ml.)",
    },
    {
        "id": "IT_157237450",
        "name": "Chivas Regal 12 Years Blended Scotch Whisky",
        "price": 495.0,
        "tags": [],
        "category": "Blended Scotch Whisky (30Ml.)",
    },
    {
        "id": "IT_157237451",
        "name": "Royal Salute Blended Scotch Whisky",
        "price": 2100.0,
        "tags": [],
        "category": "Blended Scotch Whisky (30Ml.)",
    },
    {
        "id": "IT_157237452",
        "name": "Chivas Regal 15 Years Blended Scotch Whisky",
        "price": 600.0,
        "tags": [],
        "category": "Blended Scotch Whisky (30Ml.)",
    },
    {
        "id": "IT_157237453",
        "name": "Budwiser Magnum Beer",
        "price": 300.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237454",
        "name": "Corona (can) Beer",
        "price": 400.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237455",
        "name": "Breezers Beer",
        "price": 250.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237456",
        "name": "Kingfisher Ultra (can) Beer",
        "price": 250.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237457",
        "name": "Budweiser (can)(mild) Beer",
        "price": 275.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237458",
        "name": "Heiniken (can) Beer",
        "price": 275.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237459",
        "name": "Tuborg (can) (mild) Beer",
        "price": 275.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237460",
        "name": "Tuborg Strong (can) Beer",
        "price": 300.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237461",
        "name": "Bira White (can) Beer",
        "price": 400.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237462",
        "name": "Carlsberg Smooth (can) Beer",
        "price": 275.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237463",
        "name": "Bira Beer",
        "price": 290.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237464",
        "name": "Bira (boom) Beer",
        "price": 300.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237465",
        "name": "Carlsberg Elephant (can) Beer",
        "price": 300.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237466",
        "name": "Corona (330ml) Beer",
        "price": 350.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237467",
        "name": "Ultra (330ml) Beer",
        "price": 175.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_1286182288",
        "name": "Hoegaarden Beer",
        "price": 350.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_1293186217",
        "name": "Budweiser Magnum 650ml",
        "price": 350.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_1293186637",
        "name": "Budweiser Mild 650ml",
        "price": 300.0,
        "tags": [],
        "category": "Beer",
    },
    {
        "id": "IT_157237468",
        "name": "Smirnoff Vodka",
        "price": 250.0,
        "tags": [],
        "category": "Vodka (30Ml.)",
    },
    {
        "id": "IT_157237469",
        "name": "Absolute Vodka",
        "price": 350.0,
        "tags": [],
        "category": "Vodka (30Ml.)",
    },
    {
        "id": "IT_157237470",
        "name": "Greey Goose Vodka",
        "price": 495.0,
        "tags": [],
        "category": "Vodka (30Ml.)",
    },
    {
        "id": "IT_157237471",
        "name": "Beefeater Gin",
        "price": 300.0,
        "tags": [],
        "category": "Gin (30Ml.)",
    },
    {
        "id": "IT_157237472",
        "name": "Bombay Sapphare Gin",
        "price": 350.0,
        "tags": [],
        "category": "Gin (30Ml.)",
    },
    {
        "id": "IT_157237473",
        "name": "Martini Asti Sparkling Winr",
        "price": 6000.0,
        "tags": [],
        "category": "Sparkling Wine (Bottle)",
    },
    {
        "id": "IT_157237474",
        "name": "Chandon Brut Sparkling Winr",
        "price": 7500.0,
        "tags": [],
        "category": "Sparkling Wine (Bottle)",
    },
    {
        "id": "IT_157237478",
        "name": "Jacobs Crieek Chardonnay (white)",
        "price": 820.0,
        "tags": [],
        "category": "Wine",
    },
    {
        "id": "IT_157237479",
        "name": "Glen Livet 12 Years",
        "price": 525.0,
        "tags": [],
        "category": "Whisky Single Malt (30Ml.)",
    },
    {
        "id": "IT_157237480",
        "name": "Glen Fiddich 12 Years",
        "price": 525.0,
        "tags": [],
        "category": "Whisky Single Malt (30Ml.)",
    },
    {
        "id": "IT_157237481",
        "name": "Glenmorangie",
        "price": 525.0,
        "tags": [],
        "category": "Whisky Single Malt (30Ml.)",
    },
    {
        "id": "IT_157237482",
        "name": "Indri",
        "price": 420.0,
        "tags": [],
        "category": "Whisky Single Malt (30Ml.)",
    },
    {
        "id": "IT_1285278879",
        "name": "Chocoholic",
        "price": 349.0,
        "tags": [],
        "category": "Whisky Single Malt (30Ml.)",
    },
    {
        "id": "IT_1285278892",
        "name": "Oreo Cookie Shake",
        "price": 349.0,
        "tags": [],
        "category": "Whisky Single Malt (30Ml.)",
    },
    {
        "id": "IT_1285278907",
        "name": "Kitkat Shake",
        "price": 349.0,
        "tags": [],
        "category": "Whisky Single Malt (30Ml.)",
    },
]
